### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by phoenixml** [ThisIsLibra/MalPull#1]
Hi Libra,

Feature suggestion:
1- Extend to cover other services such as VT , anyapp, joesandbox etc ...
2- Ability to search pull maldocs and samples via specific tags in addition to the hash as an option.

Thank you.

**Comment by ThisIsLibra** [comment]
Heya,

We already spoke in PM a while ago, but I'm posting the answer here for more clarity.

Regarding 1: more features were added in the previous release. More services might be added in the future.

Regarding 2: searching for samples for tags is out-of-scope for this tool, as its purely meant to download samples based upon hashes. 

If you have more specific suggestions, please post them here together with links to the API documentation.

Cheers,
Max

**Comment by ThisIsLibra** [comment]
Closing this issue as it is old, and the on-topic suggestion is being worked on over time. The out-of-scope suggestion remains out-of-scope. Thank you for actively thinking with me in this project, please do make a new issue if you find a specific services that you'd like to see implemented!

Cheers,
Max
